
export const apiEndPoints = {
  auth:{
      signup:'Company/register-company',
      login:'Auth/login',
      logout:'Auth/logout',
      refreshToken:'Auth/refresh-token',
      forgotPassword:'Auth/forgot-password/',
      resetPassword:'Auth/reset-password'
    },
  driver:{
    addEditUser:'Driver/driver',
    deleteUser:'Driver',
    getAll:'Driver/drivers'
  },
  dispatcher:{
    addEditUser:'Dispatcher/dispatcher',
    deleteUser:'Dispatcher',
    getAll:'Dispatcher/dispatchers'
  },
  vehicle:{
    addEditVehicle:'Vehicle/vehicle',
    deleteVehicle:'vehicle',
    getAll:'Vehicle/vehicles',
    vehicleList:'Vehicle/all-vehicles',
    assignVehicle:'Vehicle/vehicle-assignment',
    reAssignVehicle:'Vehicle/vehicle-assignments',
    unAssignVehicle:'Vehicle/vehicle-unassign',
    downloadVehicleCsv:'Vehicle/export/vehicles'
  },
  trip:{
    addEditTrip:'Trip/trip',
    cancelTrip:'Trip/cancel-trip',
    getAll:'Trip/trips',
    assignDriver:'Trip/assign-driver',
    unAssignDriver:'Trip/unassign-driver',
    assignedTrips:'Driver/assigned-trips',
    tripStatus:'Trip/trip-status',
    downloadTripCsv:'Trip/export/trips',
    downloadReport:'Trip/report/pdf/'
  },
  dashboard:{
    assignedVehicle:'Driver/assigned-vehicle',
    companyUserDashboard:'Dashboard/company-user-dashboard',
    dispatcherDashboard:'Dashboard/dispatcher-dashboard',
    driverDashboard:'Dashboard/driver-dashboard'
  },
  common:{
    vehicleDriverList:'Common/assignedDriverVehicles'
  }
}